### ISSUE TITLE
Gave a warning when running the build script

### ISSUE THREAD

**Issue by vipulgupta2048** [sugarlabs/Bridge#13]
```
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    bundlebuilder.start()
  File "/usr/lib/python2.7/dist-packages/sugar3/activity/bundlebuilder.py", line 475, in start
    globals()['cmd_' + options.command](config, options)
  File "/usr/lib/python2.7/dist-packages/sugar3/activity/bundlebuilder.py", line 354, in cmd_dist_xo
    packager = XOPackager(Builder(config, options.no_fail))
  File "/usr/lib/python2.7/dist-packages/sugar3/activity/bundlebuilder.py", line 216, in __init__
    self.builder.build_locale()
  File "/usr/lib/python2.7/dist-packages/sugar3/activity/bundlebuilder.py", line 147, in build_locale
    if translated_summary.find('\n') > -1:
AttributeError: 'NoneType' object has no attribute 'find'
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    bundlebuilder.start()
  File "/usr/lib/python2.7/dist-packages/sugar3/activity/bundlebuilder.py", line 475, in start
    globals()['cmd_' + options.command](config, options)
  File "/usr/lib/python2.7/dist-packages/sugar3/activity/bundlebuilder.py", line 428, in cmd_build
    builder.build()
  File "/usr/lib/python2.7/dist-packages/sugar3/activity/bundlebuilder.py", line 112, in build
    self.build_locale()
  File "/usr/lib/python2.7/dist-packages/sugar3/activity/bundlebuilder.py", line 147, in build_locale
    if translated_summary.find('\n') > -1:
AttributeError: 'NoneType' object has no attribute 'find'
****
```

**Comment by quozl** [comment]
This is an error, not a warning.  It comes from Sugar Toolkit, not the activity.

Line numbers in the traceback do not match latest release v0.112 of Sugar Toolkit.

The error does not occur when testing with v0.112, so I'll close the issue.

You should either;
* upgrade to the latest release, or;
* add the optional summary to the metadata.
